server:
    port: 8090

spring:
    profiles:
        active: joint

eureka:
    instance:
        hostname: localhost
        lease-renewal-interval-in-seconds: 300
        lease-expiration-duration-in-seconds: 900
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/