server:
    port: 9000
    
spring:
    profiles:
        active: joint
    application:
        name: login
        
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/