server:
    port: 80

spring:
    profiles:
        active: joint
    application:
        name: ribbon

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/